### PR TITLE
Slonik 26

### LINKED ISSUE #353: Support of latest slonik major version (26)
Currently, `migrator` package has `"slonik": ">= 23.0.0 < 24"` as peerDependecy limiting the accepted versions. I tested `migrator` with `slonik` 16 and it looks to be working properly.

The `typegen` package has `"slonik": ">=23.4.0"` as peerDependecy, but tests fail when slonik 26 is used.

### LINKED ISSUE #357: All types have nullabe properties
Don't see an open discussion about this, but all types at the moment have nullable properties, e.g.

```ts
sql<queries.Room>`
  SELECT
    r1.id,
    r1.uuid
  FROM room r1
`,
```

Produces:

```ts
export declare namespace queries {
  // Generated by @slonik/typegen

  /**
   * queries:
   * - `SELECT r1.id, r1.uuid FROM room r1`
   * - `SELECT r1.id, r1.uuid FROM room r1`
   */
  export type Room = {

    /**
     * regtype: `integer`
     */
    id: (number) | null,

    /**
     * regtype: `uuid`
     */
    uuid: (string) | null,
  };
}
```

Opening to track if there is anything we can do about it. I will dig myself into it too.

### PR DESCRIPTION
**Pull request by mmkal**
~Draft, not working yet. Because of issue described in https://github.com/mmkal/slonik-tools/issues/357#issuecomment-992011843 some tests for SQL files are failing. Opening now to track.~

Fixes #357 
Fixes #353 
~Supercedes 346~
Supercedes #345

### CODE REVIEW

File: packages/typegen/src/write/sql.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export function getSQLHelperContent(query: TaggedQuery, destPath: string) {
       if (cached) {
         return cached
       }
-      const content = fs.readFileSync(filepath).toString()
+      const content = fs.readFileSync(filepath).toString().replace(/\\$(\\d)/g, '#$#$1')
```
Comment (mmkal) [inline packages/typegen/src/write/sql.ts:125]: @gajus it'd be great to get your input on what to do here - basically some more context on what I'm talking about in https://github.com/gajus/slonik/issues/320#issuecomment-997380918. What's happening:

- User writes `select * from foo where bar = $1` in a file called `foobar.sql`.
- User runs slonik-typegen and a `foobar.sql.ts` file is generated containing this code
-  The generated module can then be imported with something like:

```ts
import * as fooBarQueries from './foobar.sql'

export default async () => {
   return pool.query(fooBarQueries.getFooBarQuerySync())
}
```

The problem is, under the hood `getFooBarQuerySync` now needs to add this regex replace to convert `$1` into `#$#1`. There are two problems with that:

1. It's brittle. It will do the wrong thing for queries like `select * from foo where bar = $1 or baz = '$1'`
2. It will _only_ work for slonik >=26.1.0

**Comment by gajus** [comment]
https://github.com/gajus/slonik/issues/320 should have unblocked this issue.
